### ISSUE TITLE
Cron Container Main.env Incorrect

### ISSUE THREAD

**Issue by ChestoOfGlen** [eramba/docker#19]
The crontab in the cron container references a main.env file (/var/www/eramba/app/upgrade/vendor/eramba/docker/main.env) which appears to only include the default credentials (DB_PASSWORD=docker).

I have supplied a custom password and updated it in the locations specified by the community deployment documentation, the compose file and the main.env file, but this change does not seem to have made it to the above location.

This causes the cron jobs to fail until I manually edited this file from within the cron container.

Cronjobs currently look like this:
`@hourly export $(cat /var/www/eramba/app/upgrade/vendor/eramba/docker/main.env) && /bin/sh /var/www/eramba/app/upgrade/bin/cake cron job hourly >> /var/log/cron.log 2>&1`

Either the env vars passed in by the compose file under env_file should be used, or this specific main.env file (/var/www/eramba/app/upgrade/vendor/eramba/docker/main.env) needs to be also updated by any changes made in the main.env file in the root of the Git repo.

**Comment by shrkz1** [comment]
Thanks for reporting - i created a PR (https://github.com/eramba/docker/pull/21) to fix the issue, i will leave @elsombrante to test this.
