### ISSUE TITLE
Health Check Errors Reported In Community Container Deployment

### ISSUE THREAD

**Issue by ChestoOfGlen** [eramba/docker#20]
We have identified two errors being reported by the health check having followed the community Docker deployment on Ubuntu 22.04.

One is that it is claiming that the eramba web directory is not owned by www-data. However checking the owner of the directory from within the container (via docker exec) shows that it is owned by www-data.
![image](https://user-images.githubusercontent.com/37160206/197435398-f33e1536-408c-48ab-b043-6b7a5d8b75e4.png)

The second one is claiming a missing privilege (PROCESS) in MySQL.
![image](https://user-images.githubusercontent.com/37160206/197435408-655f43e1-7c2a-4fd9-8033-4bdd4c672e43.png)

**Comment by shrkz1** [comment]
I tried to run fresh community installation and system health appears all okay to me, also @elsombrante tested this
<img width="1419" alt="image" src="https://user-images.githubusercontent.com/1518618/197543709-596d2967-fbcc-4206-b250-f8b47c0645e7.png">

if you can possibly provide additional steps you made before you got to this state, we could be of more help here.
