### ISSUE TITLE
Dashboard never shows up

### ISSUE THREAD

**Issue by dziuzdy** [eramba/docker#23]
Eramba works but the Dashboard never shows up (never ending rotating circle). There are no errors in logs.

![Zrzut ekranu_20221025_144835](https://user-images.githubusercontent.com/107858420/197777368-b62692d3-4133-4d68-a122-93fc4c3c69c2.png)
![Zrzut ekranu_20221025_144514](https://user-images.githubusercontent.com/107858420/197777377-f7d500a0-ae94-48fa-8b4e-303a3a8d4c0f.png)

**Comment by elsombrante** [comment]
Hello,

Can you give us steps to reproduce the issue? You were changing MySQL credentials or something?
In settings/system health everything is green? Worker is running?

**Comment by dziuzdy** [comment]
It's completely fresh install. Everything seems to be working properly except Dashboard.
There is one problem in settings/system:

![Zrzut ekranu_20221025_152830](https://user-images.githubusercontent.com/107858420/197786321-f8dd521d-a071-409e-90e2-cda1672dba81.png)

Crontab entries are in place - as shown in settings/cron jobs/crontab. I don't know how to solve this problem also.

![Zrzut ekranu_20221025_153027](https://user-images.githubusercontent.com/107858420/197787092-9717feb7-f925-49cd-8626-b4714cc5cc3d.png)

**Comment by shrkz1** [comment]
What platform did you start the Community Installation in ? Windows/Linux?

**Comment by dziuzdy** [comment]
It's Linux Debian 11.

**Comment by shrkz1** [comment]
Yes you are right, when changing from default mysql configuration to something else within the simple installation, CRON container wont reflect these changes and fails to run jobs correctly. Its duplicate of issue #19. You need to `docker compose -f docker-compose.simple-install.yml down` to stop containers, then apply this change https://github.com/eramba/docker/pull/21/files, and start it up again. CRON container should start working properly and system health should get green.
NOTE: it might take a minute for system health - worker to start showing "OK" status. after starting it up again
OR
Download a new version of docker (1.x) and set it up cleanly from start.

**Comment by dziuzdy** [comment]
Thank you for your help. Everything is ok now :-)
