### ISSUE TITLE
Can't bulk delete 2 or more entries in Threats

### ISSUE THREAD

**Issue by sakkarose** [eramba/docker#71]
![image](https://github.com/eramba/docker/assets/45507664/a2eb6f87-932b-4214-bb42-278eac1d1da4)
This shows up when I try to bulk delete default entries in Threats. 
Single deleting was still fine.
The account i was using is default Admin Admin.
The app version was 3.23.2 
The DB schema version was 20240104121424
And i was using Community edition.

**Comment by sakkarose** [comment]
Update: It happens on Vulnerabilities too.

So just in case this was intentional from the developers. It would be great to tell me because i'm not sure if it's a bug or something. I haven't done the courses for Eramba yet.

**Comment by elsombrante** [comment]
Hello,

Thanks for reporting. Next time please use our discussion forum to report an issue: https://discussions.eramba.org/
Int. ref.: https://github.com/eramba/eramba/issues/4670
