### ISSUE TITLE
mySQL missing permissions when running on a Cloud SQL instance

### ISSUE THREAD

**Issue by massynmantel** [eramba/docker#80]
I have configured Eramba to run in the cloud, using a cloud-provided SQL instance.  Unlike self-hosted mySQL instances, I do not have access to the `root` account.  The account I do have does have full admin powers on the database, however when I do log onto Eramba, I see the health message

```
Missing Privileges:
SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, ALTER, INDEX, PROCESS, TRIGGER
```

It seems the external mySQL database support for Eramba may not cater for externally hosted database instances.  I would appreciate any feedback if this message is a false-positive, or if there is something odd going on with the configuration.

* Running on GCP - database is a CloudSQL mySQL instance.

**Comment by elsombrante** [comment]
Hello,

Please create a topic on our forum if you have problems with installation.
https://discussions.eramba.org/
